### ISSUE TITLE
Add help permission

### ISSUE THREAD

**Issue by ghost** [DevJul1an/sTablist#12]
Ich möchte nur ungern, dass Spieler herausfinden können, welche Plug-Ins ich verwende. Es wäre dafür sehr hilfreich, wenn eine Permission zum Anzeigen der Hilfe-Seite existieren würde.

**Comment by DevJul1an** [comment]
Wird gemacht :)

**Comment by DevJul1an** [comment]
Download: https://ci.jumpy91.de/job/sTablist/
Und nicht vergessen, den AutoUpdater zu deaktivieren.
