### ISSUE TITLE
Can't change Prefix/Suffix

### ISSUE THREAD

**Issue by PQ-old** [DevJul1an/sTablist#5]
When the plugin is loaded for the first time it creates an empty groups.yml file.
No matter how I change it (even using the example from the jar), it doesn't change. Another server is also somehow stuck with [0] <name> The Best on Owner group.

**Comment by DevJul1an** [comment]
Server Version? Errors in console?

**Comment by PQ-old** [comment]
Server's version 1.12.2, the latest spigot build.
There are no errors whatsoever, and this is happening on the pre4 and pre5 builds. It worked fine before it updated

**Comment by DevJul1an** [comment]
I tried it and had no problems. But I will look into it the next days.

**Comment by TwanLuttik** [comment]
@ThexFoondom can you send your config files

**Comment by DevJul1an** [comment]
Is the issue still there?

**Comment by TwanLuttik** [comment]
https://hastebin.com/itayoyogiw.pas
here you have an example, for me its working

**Comment by TwanLuttik** [comment]
i think he did something wrong maybe @DevJul1an

**Comment by DevJul1an** [comment]
@ThexFoondom isn't responding anymore. Issue closed.
